### PR TITLE
Pre-commit hooks

### PR DESCRIPTION
**Pull request by TobeTek**
### Done:
 - Add Linting rules for `FigmaPy` 
 - Add Docstrings to all Modules and functions
 - Add `dev-requirements.txt` to hold dev dependencies

### Todo:
 - (likely) Create `CONTRIBUTING.md` with setup information for new contributors
 - Add new pre-commit hook to replace single apostrophe `'` with double apostrophe `"` in strings.

### CODE REVIEW

**Comment by hannesdelbeke** [comment]
since you run isort before black, this always fails, because they both sort their modules different.
easy solution is to disable isort, we dont need it.

fixed a few issues in a fork of your fork, check out https://github.com/hannesdelbeke/FigmaPy/tree/pre-commit-hook
 but code broke when trying to run this in production. so need to investigate. 

the core setup looks good and runs fine on my pc, but auto file fix might have broken some things. even though it shouldn't

**Comment by TobeTek** [comment]
Pulled the changes. 
I did notice some "invalid" imports when adding the docstrings. I think [this line](https://github.com/Amatobahn/FigmaPy/blob/0bd761474239fd0d564eb16b7cbaf3b213772785/FigmaPy/figmapy.py#L3) in `figma.py` is where the error is coming from. My best guess is flake8 flagged it as an unused import.

**Comment by hannesdelbeke** [comment]
yes, it errored on the same line for me.

**Comment by TobeTek** [comment]
> yes, it errored on the same line for me.

That should be fixed now. As suspected, either `black` or `autoflake8` removed a number of import statements. I reverted those to the last working commit, and turned off linting for `FigmaPy/__init__.py` and `FigmaPy/datatypes/__init__.py`

**Comment by hannesdelbeke** [comment]
this has been partialy merged in with another PR https://github.com/Amatobahn/FigmaPy/pull/19
so closing this one

**Pull request closed without merging**
