### PR TITLE
Async refactor

### PR DESCRIPTION
**Pull request by hannesdelbeke**
WORK DONE SO FAR:
- removing some dupe code from [the async PR](https://github.com/Amatobahn/FigmaPy/pull/11).
- fix some url build issues 
(likely updates that were not merged in while the async PR was being worked on, or that afterwards only were added to the synced figma session class)

TODO:
- look into adding more async support for other functions

FIXED 
- ~~also noticed random crash in the async version which is not great.~~ 
- ~~create a better async example, must have messed up my timings previously since they now results in the same times.
and thinking about it, the way it's written there is no reason to save time with the async code sample. since it onyl runs a siingle request.~~

### CODE REVIEW

**Comment by hannesdelbeke** [comment]
@TobeTek you might find this PR relevant.

**Comment by hannesdelbeke** [comment]
running sync, async, sync, async.
always crashes second time i run the async one.

timing cant be relied on, since we see sync time going down the second time we run it.
so likely the figma server is handling my request quicker.

```
sync: 21.468544721603394
async: 13.610326528549194
sync: 9.888262271881104
Error occurred attempting to make an API request. Session is closed
async: 0.0010724067687988281
None
Traceback (most recent call last):
  File "REDACTED/samples/figma/async.py", line 42, in <module>
    print(result.images)
AttributeError: 'NoneType' object has no attribute 'images'

Process finished with exit code 1
```

the second async crash seems to happen instantly, so might be related to how i'm using it?
running this twice:
```python
start = time.time()
figma_session_async = figmapy_async.AioHttpFigmaPy(token=auth_key)
loop = asyncio.get_event_loop()
result = loop.run_until_complete(figma_session_async.get_file_images(file_key=file_key, ids=node_ids))
print('async:', time.time() - start)
print(result.images)

loop.run_until_complete(figma_session_async.client.close())
```

**Comment by hannesdelbeke** [comment]
fixed the async bug, this was becayse the session was created as default kwarg value, resulting in it being shared across instances.

**Comment by hannesdelbeke** [comment]
reran the same requests a few times again:
```
sync: 12.154287099838257
async: 6.72868537902832
sync: 8.259786128997803
async: 15.6577889919281
```
now finishes without errors but no major benefit between the two.

**Comment by TobeTek** [comment]
Looks great. Seems `aiohttp.ClientSession` prefers to be spawned inside a coroutine. Going from your approach, I think it would be best to initialize `AioHttpFigmaPy.client` in `async_api_request`. That should better handle edge cases.

For speed comparisons, I wrote this up based on the code currently [here](https://github.com/hannesdelbeke/FigmaPy/tree/async-refactor).
Interesting results:
```py
import FigmaPy
import asyncio
import time

file_key = '<FILE_KEY>'
auth_key = '<TOKEN>'

# TODO create a better sample, this actually results in the same times
#  and the async version sometimes crashes randomly with a no key find in dict error

figmaPy = FigmaPy.FigmaPy(token=auth_key)
file = figmaPy.get_file(file_key)
page1 = file.document.children[0]
nodes = page1.get_children_recursively()
node_ids = [node.id for node in nodes]

def sync_request(index):
    tic = time.time()
    images = figmaPy.get_file_images(file_key=file_key, ids=node_ids)
    toc = time.time()
    time_spent = toc-tic
    print(f"Sync time {index}: {time_spent}s")
    return time_spent

def sync_main(n):
    tic = time.time()
    for i in range(n):
        sync_request(i)
    toc = time.time()
    total_time = toc - tic
    print(f"Sync Total time taken : {total_time}s")

async def async_request(index):
    tic = time.time()
    figmaPy = FigmaPy.AioHttpFigmaPy(token=auth_key)
    result = await figmaPy.get_file_images(file_key=file_key, ids=node_ids)
    toc = time.time()
    time_spent = toc-tic
    print(f"Async time {index}: {time_spent}s")
    await figmaPy.client.close()
    return time_spent

async def async_main(n):
    tic = time.time()
    
    tasks = await asyncio.gather(*[async_request(i) for i in range(n)])

    toc = time.time()
    total_time = toc-tic
    
    print(f"Async Total time taken : {total_time}s")


# Uncomment for Windows
# asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

sync_main(5)
asyncio.run(async_main(5))

```

Output:
```bash
❯ python -m sample_code.async
Sync time 0: 2.156123638153076s
Sync time 1: 1.790233850479126s
Sync time 2: 0.8593003749847412s
Sync time 3: 0.8280830383300781s
Sync time 4: 3.3903250694274902s
Sync Total time taken : 9.024065971374512s
Async time 2: 1.1118452548980713s
Async time 0: 1.252396821975708s
Async time 1: 1.3930182456970215s
Async time 3: 2.2680156230926514s
Async time 4: 3.1117067337036133s
Async Total time taken : 3.142949104309082s
```

**Comment by TobeTek** [comment]
> fixed the async bug, this was becayse the session was created as default kwarg value, resulting in it being shared across instances.

I actually never considered that. Python's "pass-by-object-reference" made it a static variable basically. Very interesting.

**Comment by hannesdelbeke** [comment]
> I actually never considered that. Python's "pass-by-object-reference" made it a static variable basically. Very interesting.

It's the same when you default lists  or dicts in kwargs. never set default values for anything that can be mutated. see [post](https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/#:~:text=In%20Python%2C%20when%20passing%20a,or%20even%20a%20class%20instance.)

**Comment by TobeTek** [comment]
> > I actually never considered that. Python's "pass-by-object-reference" made it a static variable basically. Very interesting.
> 
> It's the same when you default lists or dicts in kwargs. never set default values for anything that can be mutated. see [post](https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/#:~:text=In%20Python%2C%20when%20passing%20a,or%20even%20a%20class%20instance.)

Had a great read! Had to refactor a bit of personal code as well.

More ideas for the project:
 - Add a GitHub Action to automatically build the package (wheel, tarball) on merge to `release` or similar.
 - Add `pre-commit`  and pre-commit hooks for linting and formatting

 What do you think?

**Comment by hannesdelbeke** [comment]
> More ideas for the project:
> 
> * Add a GitHub Action to automatically build the package (wheel, tarball) on merge to `release` or similar.
> * Add `pre-commit`  and pre-commit hooks for linting and formatting
> 
> What do you think?

Nice ideas! Do you think you can make a PR?

**Comment by TobeTek** [comment]
Created a PR. Adding docstrings took a whole lot more effort that I'd envisaged.
Do have a look at #16

**Comment by TobeTek** [comment]
I also noticed that `FigmaPy` suppresses exceptions, and returns `None`. Is there any particular reason for that?

**Comment by hannesdelbeke** [comment]
> I also noticed that `FigmaPy` suppresses exceptions, and returns `None`. Is there any particular reason for that?

I believe that was how Amato wrote it originally, likely for convenience.

Merging this one in now

**Pull request merged**
